[workspace]
members = [
    "jupiter-swap-api-client",
    "example",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
solana-sdk = "3"
solana-client = "3"
solana-account-decoder = "3"
